name: Trunk Check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Trunk Check Job
    runs-on: ubuntu-latest
    concurrency:
      group: trunk-check-group
      cancel-in-progress: true

    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: payload
